import { getDefaultConfig } from "@rainbow-me/rainbowkit";
import { connectorsForWallets } from "@rainbow-me/rainbowkit";
import {
  rainbowWallet,
  metaMaskWallet,
  coinbaseWallet,
  walletConnectWallet,
  phantomWallet,
} from "@rainbow-me/rainbowkit/wallets";
import { http, createConfig } from "wagmi";
import { walletConnectProjectId } from "./walletConnectProjectId";
import {
  pulsechain,
  bsc,
  arbitrum,
  avalanche,
  polygon,
  sei,
  mainnet,
  base,
  polygonZkEvm,
  moonriver,
  fantom,
  aurora,
  optimism,
  cronos,
  gnosis,
  linea,
  scroll,
  blast,
  fuse,
  moonbeam,
  celo,
  boba,
  mantle,
  manta,
  zetachain,
  telos,
  kava,
  zksync,
  arbitrumNova,
  tron,
  metis,
  bahamut,
  mode,
  rootstock,
  merlin,
  zkLinkNova,
  taiko,
  fraxtal,
  gravity,
  morph,
  sonic,
  // Additional gas.zip source chains
  opBNB,
  berachain,
  xLayer,
  viction,
  zora,
  superposition,
  plumeMainnet,
  flowMainnet,
  katana,
  monad,
  unichain,
  worldchain,
  immutableZkEvm,
  robinhood,
  megaeth,
  vana,
  ronin,
  plasma,
  etherlink,
  lisk,
  flare,
  zeroGMainnet,
  bob,
  stable,
  somnia,
  ink,
  soneium,
  lens,
  xdc,
  kaia,
  hemi,
  superseed,
  abstract,
  hyperEvm,
  injective,
  apeChain,
} from "wagmi/chains";
import { defineChain } from "viem";

// Not in viem's chain list; details from the gas.zip /v2/chains API
const pharos = defineChain({
  id: 1672,
  name: "Pharos",
  nativeCurrency: { name: "PROS", symbol: "PROS", decimals: 18 },
  rpcUrls: {
    default: { http: ["https://rpc.pharos.xyz"] },
  },
  blockExplorers: {
    default: { name: "SocialScan", url: "https://pharos.socialscan.io" },
  },
});

// Wallet configuration for bridge
const bridgeConnectors = connectorsForWallets(
  [
    {
      groupName: "Suggested",
      wallets: [
        metaMaskWallet,
        phantomWallet,
        rainbowWallet,
        coinbaseWallet,
        walletConnectWallet,
      ],
    },
  ],
  { appName: "RainbowKit Bridge", projectId: walletConnectProjectId }
);

export const bridgeConfig = getDefaultConfig({
  appName: "Emplseal Bridge",
  projectId: walletConnectProjectId,
  chains: [
    pulsechain,
    mainnet,
    bsc,
    arbitrum,
    avalanche,
    polygon,
    optimism,
    cronos,
    base,
    blast,
    manta,
    zetachain,
    zksync,
    sei,
    polygonZkEvm,
    moonriver,
    fantom,
    aurora,
    gnosis,
    linea,
    scroll,
    fuse,
    moonbeam,
    celo,
    boba,
    mantle,
    telos,
    kava,
    arbitrumNova,
    tron,
    metis,
    bahamut,
    mode,
    rootstock,
    merlin,
    zkLinkNova,
    taiko,
    fraxtal,
    gravity,
    morph,
    sonic,
    opBNB,
    berachain,
    xLayer,
    viction,
    zora,
    superposition,
    plumeMainnet,
    flowMainnet,
    katana,
    monad,
    unichain,
    worldchain,
    immutableZkEvm,
    robinhood,
    megaeth,
    vana,
    ronin,
    plasma,
    etherlink,
    lisk,
    flare,
    zeroGMainnet,
    bob,
    stable,
    somnia,
    ink,
    soneium,
    lens,
    xdc,
    kaia,
    hemi,
    superseed,
    abstract,
    hyperEvm,
    injective,
    apeChain,
    pharos,
  ],
  ssr: true,
  connectors: bridgeConnectors,
});
